# Use trusty environment for a up-to-date version of autotools
sudo: required
dist: trusty
language: c
matrix:
  include:
    - os: linux
      compiler: clang
      env: BUILD_TYPE=default CFLAGS=-fsanitize=address
    - os: linux
      compiler: clang
      env: BUILD_TYPE=default CFLAGS=-fsanitize=undefined
    - os: linux
      compiler: gcc
      env: BUILD_TYPE=default CFLAGS=-fsanitize=address
    - os: osx
      compiler: clang
      env: BUILD_TYPE=default CFLAGS=-fsanitize=address
    - os: osx
      compiler: clang
      env: BUILD_TYPE=mandoc
install:
  - |
    if [ $BUILD_TYPE = mandoc ]; then
      brew install mandoc
    fi
script:
  - |
    if [ $BUILD_TYPE = default ]; then
      ./autogen.sh
      ./configure || (cat config.log; exit 1)
      make || exit 1
      make distcheck || (find . -name test-suite.log | xargs -t cat; exit 1)
    fi
  - |
    if [ $BUILD_TYPE = mandoc ]; then
      mandoc -Tlint pick.1
    fi
